FROM ubuntu:18.04

LABEL maintainer="Shirong Hao <shirong@linux.alibaba.com>"

RUN apt-get update && apt-get install -y autoconf gcc g++ make wget git \
    libseccomp-dev binutils-dev libprotoc-dev protobuf-compiler \
    pkg-config libssl-dev openssl libtool file curl

WORKDIR /root

# install prortobuf-c
RUN wget https://github.com/protobuf-c/protobuf-c/archive/v1.3.1.tar.gz &&\
    tar -zxvf v1.3.1.tar.gz && cd protobuf-c-1.3.1 && ./autogen.sh && \
    ./configure && make && make install

# install go
RUN wget https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz && \
    tar -zxvf go1.14.2.linux-amd64.tar.gz -C /usr/lib && \
    rm -rf go1.14.2.linux-amd64.tar.gz

# configure GOPATH and GOROOT
ENV GOROOT       /usr/lib/go
ENV GOPATH       /root/gopath
ENV PATH         $PATH:$GOROOT/bin:$GOPATH/bin
ENV GOPROXY      "https://mirrors.aliyun.com/goproxy,direct"
ENV GO111MODULE  on

# install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
ENV PATH         /root/.cargo/bin:$PATH

# install sgx
RUN [ ! -f sgx_linux_x64_sdk_2.13.100.4.bin ] && \
    wget https://download.01.org/intel-sgx/sgx-linux/2.13/distro/ubuntu18.04-server/sgx_linux_x64_sdk_2.13.100.4.bin && \
    chmod +x sgx_linux_x64_sdk_2.13.100.4.bin &&  echo -e 'no\n/opt/intel\n' | ./sgx_linux_x64_sdk_2.13.100.4.bin && \
    rm -rf sgx_linux_x64_sdk_2.13.100.4.bin

RUN echo 'deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu bionic main' | tee /etc/apt/sources.list.d/intel-sgx.list && wget -qO - https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | apt-key add -

RUN apt-get update -y  && apt-get install -y libsgx-dcap-quote-verify libsgx-dcap-quote-verify-dev libsgx-dcap-ql-dev libsgx-uae-service
