FROM registry.cn-hangzhou.aliyuncs.com/alinux/aliyunlinux:latest

LABEL maintainer="Shirong Hao <shirong@linux.alibaba.com>"

# Install alinux-release-experimentals prior to others to work around
# the issue "Error: Package: glibc-2.17-323.1.al7.i686 (updates)"
RUN yum install -y alinux-release-experimentals

ENV PROTOBUF_VERSION 2.5.0
ENV PROTOBUF_C_VERSION 1.0.2

# Use mirrors.aliyun.com instead of mirrors.cloud.aliyuncs.com to work
# around unknown name or service error when retrieving key
RUN rpm --import http://mirrors.aliyun.com/epel/RPM-GPG-KEY-EPEL-7

RUN yum install -y \
    which wget git make autoconf libtool openssl yum-utils file \
    libseccomp-devel binutils-devel openssl-devel devtoolset-9-toolchain cmake3 \
    protobuf-devel-$PROTOBUF_VERSION protobuf-c-devel-$PROTOBUF_C_VERSION

RUN echo "source /opt/rh/devtoolset-9/enable" > /root/.bashrc

WORKDIR /root

# install go
RUN wget https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz && \
    tar -zxvf go1.14.2.linux-amd64.tar.gz -C /usr/lib && \
    rm -f go1.14.2.linux-amd64.tar.gz

# configure GOPATH and GOROOT
ENV GOROOT       /usr/lib/go
ENV GOPATH       /root/gopath
ENV PATH         $PATH:$GOROOT/bin:$GOPATH/bin
ENV GOPROXY      "https://mirrors.aliyun.com/goproxy,direct"
ENV GO111MODULE  on

# install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
ENV PATH         /root/.cargo/bin:$PATH

# Configure Alibaba Cloud TEE SDK yum repo
RUN yum-config-manager --add-repo \
	https://enclave-cn-beijing.oss-cn-beijing.aliyuncs.com/repo/alinux/enclave-expr.repo

# Install SGX Runtime
RUN yum install --nogpgcheck -y libsgx-ae-le libsgx-ae-pce libsgx-ae-qe3 libsgx-ae-qve \
    libsgx-aesm-ecdsa-plugin libsgx-aesm-launch-plugin libsgx-aesm-pce-plugin libsgx-aesm-quote-ex-plugin \
    libsgx-dcap-default-qpl libsgx-dcap-ql libsgx-dcap-quote-verify \
    libsgx-enclave-common libsgx-launch libsgx-pce-logic libsgx-qe3-logic libsgx-quote-ex \
    libsgx-ra-network libsgx-ra-uefi libsgx-uae-service libsgx-urts sgx-ra-service \
    sgx-aesm-service

# Install Alibaba Cloud TEE SDK
RUN yum install --nogpgcheck -y teesdk

RUN echo "source /opt/alibaba/teesdk/intel/sgxsdk/environment" >> /root/.bashrc
RUN ln -sf /usr/bin/cmake3 /usr/bin/cmake
