FROM registry.cn-hangzhou.aliyuncs.com/alinux/aliyunlinux

LABEL maintainer="Shirong Hao <shirong@linux.alibaba.com>"

RUN yum install -y which wget git make gcc gcc-c++ \
    libseccomp-devel binutils-devel alinux-release-experimentals \
    protobuf protobuf-devel protobuf-c-devel openssl openssl-devel yum-utils

WORKDIR /root

# install go
RUN wget https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz && \
    tar -zxvf go1.14.2.linux-amd64.tar.gz -C /usr/lib && \
    rm -rf go1.14.2.linux-amd64.tar.gz

# configure GOPATH and GOROOT
ENV GOROOT       /usr/lib/go
ENV GOPATH       /root/gopath
ENV PATH         $PATH:$GOROOT/bin:$GOPATH/bin
ENV GOPROXY      "https://mirrors.aliyun.com/goproxy,direct"
ENV GO111MODULE  on

# install SGX
RUN [ ! -f sgx_rpm_local_repo.tar.gz ] && \
    wget -c https://mirrors.openanolis.org/inclavare-containers/alinux2/sgx_rpm_local_repo.tar.gz && \
    tar xzf sgx_rpm_local_repo.tar.gz && \
    yum-config-manager --add-repo file:/root/sgx_rpm_local_repo && \
    yum makecache && rm -rf sgx_rpm_local_repo.tar.gz

RUN yum install --nogpgcheck -y libsgx-dcap-quote-verify-devel
