/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: aesm.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "aesm.pb-c.h"
void   aesm_service_request__get_launch_token__init
                     (AesmServiceRequest__GetLaunchToken         *message)
{
  static const AesmServiceRequest__GetLaunchToken init_value = AESM_SERVICE_REQUEST__GET_LAUNCH_TOKEN__INIT;
  *message = init_value;
}
void   aesm_service_request__init
                     (AesmServiceRequest         *message)
{
  static const AesmServiceRequest init_value = AESM_SERVICE_REQUEST__INIT;
  *message = init_value;
}
size_t aesm_service_request__get_packed_size
                     (const AesmServiceRequest *message)
{
  assert(message->base.descriptor == &aesm_service_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aesm_service_request__pack
                     (const AesmServiceRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aesm_service_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aesm_service_request__pack_to_buffer
                     (const AesmServiceRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aesm_service_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AesmServiceRequest *
       aesm_service_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AesmServiceRequest *)
     protobuf_c_message_unpack (&aesm_service_request__descriptor,
                                allocator, len, data);
}
void   aesm_service_request__free_unpacked
                     (AesmServiceRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &aesm_service_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   aesm_service_response__get_launch_token__init
                     (AesmServiceResponse__GetLaunchToken         *message)
{
  static const AesmServiceResponse__GetLaunchToken init_value = AESM_SERVICE_RESPONSE__GET_LAUNCH_TOKEN__INIT;
  *message = init_value;
}
void   aesm_service_response__init
                     (AesmServiceResponse         *message)
{
  static const AesmServiceResponse init_value = AESM_SERVICE_RESPONSE__INIT;
  *message = init_value;
}
size_t aesm_service_response__get_packed_size
                     (const AesmServiceResponse *message)
{
  assert(message->base.descriptor == &aesm_service_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aesm_service_response__pack
                     (const AesmServiceResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aesm_service_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aesm_service_response__pack_to_buffer
                     (const AesmServiceResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aesm_service_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AesmServiceResponse *
       aesm_service_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AesmServiceResponse *)
     protobuf_c_message_unpack (&aesm_service_response__descriptor,
                                allocator, len, data);
}
void   aesm_service_response__free_unpacked
                     (AesmServiceResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &aesm_service_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor aesm_service_request__get_launch_token__field_descriptors[4] =
{
  {
    "enclavehash",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(AesmServiceRequest__GetLaunchToken, enclavehash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modulus",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(AesmServiceRequest__GetLaunchToken, modulus),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attributes",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(AesmServiceRequest__GetLaunchToken, attributes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AesmServiceRequest__GetLaunchToken, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aesm_service_request__get_launch_token__field_indices_by_name[] = {
  2,   /* field[2] = attributes */
  0,   /* field[0] = enclavehash */
  1,   /* field[1] = modulus */
  3,   /* field[3] = timeout */
};
static const ProtobufCIntRange aesm_service_request__get_launch_token__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 9, 3 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor aesm_service_request__get_launch_token__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AesmServiceRequest.GetLaunchToken",
  "GetLaunchToken",
  "AesmServiceRequest__GetLaunchToken",
  "",
  sizeof(AesmServiceRequest__GetLaunchToken),
  4,
  aesm_service_request__get_launch_token__field_descriptors,
  aesm_service_request__get_launch_token__field_indices_by_name,
  2,  aesm_service_request__get_launch_token__number_ranges,
  (ProtobufCMessageInit) aesm_service_request__get_launch_token__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor aesm_service_request__field_descriptors[1] =
{
  {
    "getLaunchToken",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AesmServiceRequest, getlaunchtoken),
    &aesm_service_request__get_launch_token__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aesm_service_request__field_indices_by_name[] = {
  0,   /* field[0] = getLaunchToken */
};
static const ProtobufCIntRange aesm_service_request__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor aesm_service_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AesmServiceRequest",
  "AesmServiceRequest",
  "AesmServiceRequest",
  "",
  sizeof(AesmServiceRequest),
  1,
  aesm_service_request__field_descriptors,
  aesm_service_request__field_indices_by_name,
  1,  aesm_service_request__number_ranges,
  (ProtobufCMessageInit) aesm_service_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor aesm_service_response__get_launch_token__field_descriptors[2] =
{
  {
    "error",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AesmServiceResponse__GetLaunchToken, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(AesmServiceResponse__GetLaunchToken, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aesm_service_response__get_launch_token__field_indices_by_name[] = {
  0,   /* field[0] = error */
  1,   /* field[1] = token */
};
static const ProtobufCIntRange aesm_service_response__get_launch_token__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor aesm_service_response__get_launch_token__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AesmServiceResponse.GetLaunchToken",
  "GetLaunchToken",
  "AesmServiceResponse__GetLaunchToken",
  "",
  sizeof(AesmServiceResponse__GetLaunchToken),
  2,
  aesm_service_response__get_launch_token__field_descriptors,
  aesm_service_response__get_launch_token__field_indices_by_name,
  1,  aesm_service_response__get_launch_token__number_ranges,
  (ProtobufCMessageInit) aesm_service_response__get_launch_token__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor aesm_service_response__field_descriptors[1] =
{
  {
    "getLaunchToken",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AesmServiceResponse, getlaunchtoken),
    &aesm_service_response__get_launch_token__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aesm_service_response__field_indices_by_name[] = {
  0,   /* field[0] = getLaunchToken */
};
static const ProtobufCIntRange aesm_service_response__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor aesm_service_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AesmServiceResponse",
  "AesmServiceResponse",
  "AesmServiceResponse",
  "",
  sizeof(AesmServiceResponse),
  1,
  aesm_service_response__field_descriptors,
  aesm_service_response__field_indices_by_name,
  1,  aesm_service_response__number_ranges,
  (ProtobufCMessageInit) aesm_service_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
