// Code generated by protoc-gen-go. DO NOT EDIT.
// source: enclave.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Enclave struct {
	Fd                   int64            `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"`
	Nr                   int64            `protobuf:"varint,2,opt,name=nr,proto3" json:"nr,omitempty"`
	Layout               []*Enclavelayout `protobuf:"bytes,3,rep,name=layout,proto3" json:"layout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Enclave) Reset()         { *m = Enclave{} }
func (m *Enclave) String() string { return proto.CompactTextString(m) }
func (*Enclave) ProtoMessage()    {}
func (*Enclave) Descriptor() ([]byte, []int) {
	return fileDescriptor_69ce47264ef90dcc, []int{0}
}

func (m *Enclave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Enclave.Unmarshal(m, b)
}
func (m *Enclave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Enclave.Marshal(b, m, deterministic)
}
func (m *Enclave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Enclave.Merge(m, src)
}
func (m *Enclave) XXX_Size() int {
	return xxx_messageInfo_Enclave.Size(m)
}
func (m *Enclave) XXX_DiscardUnknown() {
	xxx_messageInfo_Enclave.DiscardUnknown(m)
}

var xxx_messageInfo_Enclave proto.InternalMessageInfo

func (m *Enclave) GetFd() int64 {
	if m != nil {
		return m.Fd
	}
	return 0
}

func (m *Enclave) GetNr() int64 {
	if m != nil {
		return m.Nr
	}
	return 0
}

func (m *Enclave) GetLayout() []*Enclavelayout {
	if m != nil {
		return m.Layout
	}
	return nil
}

type Enclavelayout struct {
	Addr                 uint64        `protobuf:"varint,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Size                 uint64        `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Prot                 *EnclavePerms `protobuf:"bytes,3,opt,name=prot,proto3" json:"prot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Enclavelayout) Reset()         { *m = Enclavelayout{} }
func (m *Enclavelayout) String() string { return proto.CompactTextString(m) }
func (*Enclavelayout) ProtoMessage()    {}
func (*Enclavelayout) Descriptor() ([]byte, []int) {
	return fileDescriptor_69ce47264ef90dcc, []int{1}
}

func (m *Enclavelayout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Enclavelayout.Unmarshal(m, b)
}
func (m *Enclavelayout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Enclavelayout.Marshal(b, m, deterministic)
}
func (m *Enclavelayout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Enclavelayout.Merge(m, src)
}
func (m *Enclavelayout) XXX_Size() int {
	return xxx_messageInfo_Enclavelayout.Size(m)
}
func (m *Enclavelayout) XXX_DiscardUnknown() {
	xxx_messageInfo_Enclavelayout.DiscardUnknown(m)
}

var xxx_messageInfo_Enclavelayout proto.InternalMessageInfo

func (m *Enclavelayout) GetAddr() uint64 {
	if m != nil {
		return m.Addr
	}
	return 0
}

func (m *Enclavelayout) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Enclavelayout) GetProt() *EnclavePerms {
	if m != nil {
		return m.Prot
	}
	return nil
}

type EnclavePerms struct {
	Read                 bool     `protobuf:"varint,1,opt,name=read,proto3" json:"read,omitempty"`
	Write                bool     `protobuf:"varint,2,opt,name=write,proto3" json:"write,omitempty"`
	Execute              bool     `protobuf:"varint,3,opt,name=execute,proto3" json:"execute,omitempty"`
	Share                bool     `protobuf:"varint,4,opt,name=share,proto3" json:"share,omitempty"`
	Private              bool     `protobuf:"varint,5,opt,name=private,proto3" json:"private,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnclavePerms) Reset()         { *m = EnclavePerms{} }
func (m *EnclavePerms) String() string { return proto.CompactTextString(m) }
func (*EnclavePerms) ProtoMessage()    {}
func (*EnclavePerms) Descriptor() ([]byte, []int) {
	return fileDescriptor_69ce47264ef90dcc, []int{2}
}

func (m *EnclavePerms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnclavePerms.Unmarshal(m, b)
}
func (m *EnclavePerms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnclavePerms.Marshal(b, m, deterministic)
}
func (m *EnclavePerms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnclavePerms.Merge(m, src)
}
func (m *EnclavePerms) XXX_Size() int {
	return xxx_messageInfo_EnclavePerms.Size(m)
}
func (m *EnclavePerms) XXX_DiscardUnknown() {
	xxx_messageInfo_EnclavePerms.DiscardUnknown(m)
}

var xxx_messageInfo_EnclavePerms proto.InternalMessageInfo

func (m *EnclavePerms) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

func (m *EnclavePerms) GetWrite() bool {
	if m != nil {
		return m.Write
	}
	return false
}

func (m *EnclavePerms) GetExecute() bool {
	if m != nil {
		return m.Execute
	}
	return false
}

func (m *EnclavePerms) GetShare() bool {
	if m != nil {
		return m.Share
	}
	return false
}

func (m *EnclavePerms) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

func init() {
	proto.RegisterType((*Enclave)(nil), "v1alpha1.Enclave")
	proto.RegisterType((*Enclavelayout)(nil), "v1alpha1.Enclavelayout")
	proto.RegisterType((*EnclavePerms)(nil), "v1alpha1.EnclavePerms")
}

func init() {
	proto.RegisterFile("enclave.proto", fileDescriptor_69ce47264ef90dcc)
}

var fileDescriptor_69ce47264ef90dcc = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4f, 0x83, 0x40,
	0x10, 0xc5, 0x43, 0xd9, 0xb6, 0x64, 0xb4, 0x1e, 0x36, 0x46, 0xf7, 0xd8, 0x70, 0x6a, 0x3c, 0x60,
	0xaa, 0x9f, 0xc1, 0xbb, 0xd9, 0xa3, 0xb7, 0x11, 0xc6, 0x94, 0x04, 0x81, 0x0c, 0x14, 0xff, 0x1c,
	0xfd, 0xe4, 0xee, 0xce, 0xd0, 0x44, 0xd3, 0xdb, 0x7b, 0x6f, 0x7e, 0x79, 0x0f, 0x16, 0x36, 0xd4,
	0x96, 0x0d, 0x4e, 0x54, 0xf4, 0xdc, 0x8d, 0x9d, 0xcd, 0xa6, 0x3d, 0x36, 0xfd, 0x01, 0xf7, 0xf9,
	0x0b, 0xac, 0x9f, 0xf4, 0x64, 0xaf, 0x60, 0xf1, 0x56, 0xb9, 0x64, 0x9b, 0xec, 0x52, 0x1f, 0x54,
	0xf4, 0x2d, 0xbb, 0x85, 0xfa, 0x96, 0xed, 0x3d, 0xac, 0x1a, 0xfc, 0xea, 0x8e, 0xa3, 0x4b, 0xb7,
	0xe9, 0xee, 0xe2, 0xe1, 0xb6, 0x38, 0xb5, 0x14, 0x73, 0x85, 0x9e, 0xfd, 0x8c, 0xe5, 0x25, 0x6c,
	0xfe, 0x1d, 0xac, 0x05, 0x83, 0x55, 0xc5, 0xb2, 0x61, 0xbc, 0xe8, 0x98, 0x0d, 0xf5, 0x37, 0xc9,
	0x4e, 0xc8, 0xa2, 0xb6, 0x77, 0x60, 0xe2, 0x77, 0x86, 0x9d, 0x24, 0xec, 0xdc, 0x9c, 0xed, 0x3c,
	0x13, 0xbf, 0x0f, 0x5e, 0x98, 0xfc, 0x27, 0x81, 0xcb, 0xbf, 0x71, 0x2c, 0x64, 0x42, 0xfd, 0x91,
	0xcc, 0x8b, 0xb6, 0xd7, 0xb0, 0xfc, 0xe0, 0x7a, 0xd4, 0x95, 0xcc, 0xab, 0xb1, 0x0e, 0xd6, 0xf4,
	0x49, 0xe5, 0x31, 0xe4, 0xa9, 0xe4, 0x27, 0x1b, 0xf9, 0xe1, 0x80, 0x4c, 0xce, 0x28, 0x2f, 0x26,
	0xf2, 0x3d, 0xd7, 0x13, 0x06, 0x7e, 0xa9, 0xfc, 0x6c, 0x5f, 0x57, 0xf2, 0xac, 0x8f, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xb1, 0x5c, 0xcf, 0xae, 0x67, 0x01, 0x00, 0x00,
}
