// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shelterd-attestation.proto

package shelterd_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AttestChallenge struct {
	Nonce                []byte   `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttestChallenge) Reset()         { *m = AttestChallenge{} }
func (m *AttestChallenge) String() string { return proto.CompactTextString(m) }
func (*AttestChallenge) ProtoMessage()    {}
func (*AttestChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_01dafffd60f2135c, []int{0}
}

func (m *AttestChallenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestChallenge.Unmarshal(m, b)
}
func (m *AttestChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestChallenge.Marshal(b, m, deterministic)
}
func (m *AttestChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestChallenge.Merge(m, src)
}
func (m *AttestChallenge) XXX_Size() int {
	return xxx_messageInfo_AttestChallenge.Size(m)
}
func (m *AttestChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_AttestChallenge proto.InternalMessageInfo

func (m *AttestChallenge) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

type AttestResponse struct {
	Quote                []byte   `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttestResponse) Reset()         { *m = AttestResponse{} }
func (m *AttestResponse) String() string { return proto.CompactTextString(m) }
func (*AttestResponse) ProtoMessage()    {}
func (*AttestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01dafffd60f2135c, []int{1}
}

func (m *AttestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestResponse.Unmarshal(m, b)
}
func (m *AttestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestResponse.Marshal(b, m, deterministic)
}
func (m *AttestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestResponse.Merge(m, src)
}
func (m *AttestResponse) XXX_Size() int {
	return xxx_messageInfo_AttestResponse.Size(m)
}
func (m *AttestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AttestResponse proto.InternalMessageInfo

func (m *AttestResponse) GetQuote() []byte {
	if m != nil {
		return m.Quote
	}
	return nil
}

func init() {
	proto.RegisterType((*AttestChallenge)(nil), "shelterd_proto.AttestChallenge")
	proto.RegisterType((*AttestResponse)(nil), "shelterd_proto.AttestResponse")
}

func init() {
	proto.RegisterFile("shelterd-attestation.proto", fileDescriptor_01dafffd60f2135c)
}

var fileDescriptor_01dafffd60f2135c = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0xce, 0x48, 0xcd,
	0x29, 0x49, 0x2d, 0x4a, 0xd1, 0x4d, 0x2c, 0x29, 0x49, 0x2d, 0x2e, 0x49, 0x2c, 0xc9, 0xcc, 0xcf,
	0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x83, 0xc9, 0xc5, 0x83, 0xf9, 0x4a, 0xea, 0x5c,
	0xfc, 0x8e, 0x60, 0x45, 0xce, 0x19, 0x89, 0x39, 0x39, 0xa9, 0x79, 0xe9, 0xa9, 0x42, 0x22, 0x5c,
	0xac, 0x79, 0xf9, 0x79, 0xc9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x10, 0x8e, 0x92,
	0x1a, 0x17, 0x1f, 0x44, 0x61, 0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x31, 0x58, 0x5d, 0x61, 0x69,
	0x7e, 0x49, 0xaa, 0x04, 0x13, 0x44, 0x1d, 0x98, 0x63, 0x94, 0xca, 0xc5, 0xed, 0x88, 0xb0, 0x55,
	0x28, 0x8c, 0x4b, 0xd0, 0x33, 0x2f, 0xb3, 0x24, 0x33, 0xb1, 0x24, 0x15, 0x61, 0x83, 0xbc, 0x1e,
	0xaa, 0x2b, 0xf4, 0xd0, 0x9c, 0x20, 0x25, 0x87, 0x5d, 0x01, 0xcc, 0x6a, 0x25, 0x86, 0x24, 0x36,
	0xb0, 0xb8, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x59, 0x89, 0x9c, 0xec, 0x00, 0x00, 0x00,
}
