[package]
name = "opa"
version = "0.1.0"
authors = ["Emison Lu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
libc = "0.2"