FROM centos:8.2.2004 AS builder

LABEL maintainer="Shirong Hao <shirong@linux.alibaba.com>"

RUN dnf clean all && rm -r /var/cache/dnf && \
    dnf --enablerepo=PowerTools install -y \
      make gcc rpm-build protobuf-c autoconf libtool gcc-c++ cmake libarchive \
      wget git yum-utils file clang which vim \
      glibc-static \
      libseccomp-devel openssl-devel binutils-devel protobuf-c-devel

WORKDIR /root

RUN mkdir /root/gopath

# install golang
RUN wget https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz && \
    tar -zxvf go1.14.2.linux-amd64.tar.gz -C /usr/lib && \
    rm -f go1.14.2.linux-amd64.tar.gz

# configure GOPATH and GOROOT
ENV GOROOT       /usr/lib/go
ENV GOPATH       /root/gopath
ENV PATH         $PATH:$GOROOT/bin:$GOPATH/bin
ENV GO111MODULE  on

# install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
ENV PATH         /root/.cargo/bin:$PATH

FROM builder AS eaa

# download and install containerd 1.5.3
RUN wget https://github.com/containerd/containerd/releases/download/v1.5.3/cri-containerd-cni-1.5.3-linux-amd64.tar.gz && \
    tar zxvf cri-containerd-cni-1.5.3-linux-amd64.tar.gz && \
    cp -rf etc/* /etc/ && cp -rf opt/* /opt/ && \
    cp -f usr/local/bin/* /usr/local/bin/ && \
    rm -rf cri-containerd-cni-1.5.3-linux-amd64.tar.gz etc opt usr
	
# configue ocicrypt keyprovider
RUN mkdir -p /etc/containerd/ocicrypt/keys

# configure containerd
RUN containerd config default > config.toml && \
    sed -i "s#k8s.gcr.io/pause:3.5#registry.cn-hangzhou.aliyuncs.com/acs/pause-amd64:3.1#g" config.toml && \
    sed -i 's/\(snapshotter = \)"overlayfs"/\1"native"/' config.toml && \
    cp -f config.toml /etc/containerd

# build and install skopeo
RUN git clone https://github.com/containers/skopeo $GOPATH/src/github.com/containers/skopeo && \
    dnf --enablerepo=PowerTools install -y gpgme-devel libassuan-devel device-mapper-devel && \
    cd $GOPATH/src/github.com/containers/skopeo && make bin/skopeo && \
    cp -f $GOPATH/src/github.com/containers/skopeo/bin/skopeo /usr/local/bin/

# configue crictl
RUN rm -rf /etc/crictl.yaml && \
    echo -e "runtime-endpoint: unix:///run/containerd/containerd.sock\nimage-endpoint: unix:///run/containerd/containerd.sock\ntimeout: 2\ndebug: true" > /etc/crictl.yaml

FROM builder

ENV SGX_SDK_VERSION         2.14
ENV SGX_SDK_RELEASE_NUMBER  2.14.100.2

# install LVI binutils for rats-tls build
RUN wget https://download.01.org/intel-sgx/sgx-linux/$SGX_SDK_VERSION/as.ld.objdump.gold.r3.tar.gz && \
     tar -zxvf as.ld.objdump.gold.r3.tar.gz && cp -rf external/toolset/centos8.2/* /usr/local/bin/ && \
     rm -rf external && rm -rf as.ld.objdump.gold.r3.tar.gz

# install docker
RUN dnf --enablerepo=PowerTools install -y iptables && \
    wget https://download.docker.com/linux/static/stable/x86_64/docker-19.03.8.tgz && \
    tar -zxvf docker-19.03.8.tgz && mv docker/* /usr/bin && rm -rf docker && rm -f docker-19.03.8.tgz

# configure the rune runtime of docker
RUN mkdir -p /etc/docker && \
    echo -e "{\n\t\"runtimes\": {\n\t\t\"rune\": {\n\t\t\t\"path\": \"/usr/local/bin/rune\",\n\t\t\t\"runtimeArgs\": []\n\t\t}\n\t}\n}" >> /etc/docker/daemon.json

# install Intel SGX SDK and DCAP
RUN [ ! -f sgx_linux_x64_sdk_$SGX_SDK_RELEASE_NUMBER.bin ] && \
    wget -c https://download.01.org/intel-sgx/sgx-linux/$SGX_SDK_VERSION/distro/centos8.2-server/sgx_linux_x64_sdk_$SGX_SDK_RELEASE_NUMBER.bin && \
    chmod +x sgx_linux_x64_sdk_$SGX_SDK_RELEASE_NUMBER.bin && echo -e 'no\n/opt/intel\n' | ./sgx_linux_x64_sdk_$SGX_SDK_RELEASE_NUMBER.bin && \
    rm -f sgx_linux_x64_sdk_$SGX_SDK_RELEASE_NUMBER.bin

RUN [ ! -f sgx_rpm_local_repo.tgz ] && \
    wget -c https://download.01.org/intel-sgx/sgx-linux/$SGX_SDK_VERSION/distro/centos8.2-server/sgx_rpm_local_repo.tgz && \
    tar xzf sgx_rpm_local_repo.tgz && \
    yum-config-manager --add-repo sgx_rpm_local_repo && \
    yum makecache && rm -f sgx_rpm_local_repo.tgz

RUN yum install --nogpgcheck -y \
    libsgx-uae-service libsgx-dcap-default-qpl \
    libsgx-dcap-quote-verify-devel libsgx-dcap-ql-devel

# install the packages need by skopeo
RUN dnf --enablerepo=PowerTools install -y gpgme-devel device-mapper-devel

# remove native contanerd 1.2.13
RUN rm -rf /usr/bin/containerd /usr/bin/containerd-shim /usr/bin/ctr

# install OPA go dependencies
RUN go get github.com/open-policy-agent/opa@v0.30.2
RUN curl -L -o opa https://openpolicyagent.org/downloads/v0.30.2/opa_linux_amd64_static
RUN chmod 755 ./opa && mv opa /usr/local/bin/

# copy binary and configure files
COPY --from=eaa /opt/cni                             /opt/cni
COPY --from=eaa /etc/containerd                      /etc/containerd
COPY --from=eaa /etc/cni                             /etc/cni
COPY --from=eaa /etc/crictl.yaml                     /etc
COPY --from=eaa /usr/local/bin                       /usr/local/bin
COPY --from=eaa /usr/local/bin/containerd            /usr/bin/
COPY --from=eaa /usr/local/bin/containerd-shim       /usr/bin/
COPY --from=eaa /usr/local/bin/ctr                   /usr/bin/
