FROM registry.cn-hangzhou.aliyuncs.com/alinux/aliyunlinux

LABEL maintainer="Shirong Hao <shirong@linux.alibaba.com>"

# Install alinux-release-experimentals prior to others to work around
# the issue "Error: Package: glibc-2.17-323.1.al7.i686 (updates)"
RUN yum clean all && yum install -y alinux-release-experimentals

ENV PROTOBUF_VERSION 2.5.0
ENV PROTOBUF_C_VERSION 1.0.2

# Use mirrors.aliyun.com instead of mirrors.cloud.aliyuncs.com to work
# around unknown name or service error when retrieving key
RUN rpm --import http://mirrors.aliyun.com/epel/RPM-GPG-KEY-EPEL-7

RUN yum install -y \
    autoconf libtool rpm-build devtoolset-9-toolchain protobuf-c-$PROTOBUF_C_VERSION cmake3 \
    wget make openssl git clang yum-utils file which vim \
    libseccomp-devel openssl-devel binutils-devel protobuf-c-devel-$PROTOBUF_C_VERSION

RUN echo "source /opt/rh/devtoolset-9/enable" > /root/.bashrc

WORKDIR /root

RUN mkdir /root/gopath

# install golang
RUN wget https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz && \
    tar -zxvf go1.14.2.linux-amd64.tar.gz -C /usr/lib && \
    rm -f go1.14.2.linux-amd64.tar.gz

# configure GOPATH and GOROOT
ENV GOROOT       /usr/lib/go
ENV GOPATH       /root/gopath
ENV PATH         $PATH:$GOROOT/bin:$GOPATH/bin
ENV GO111MODULE  on

# install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
ENV PATH         /root/.cargo/bin:$PATH

# install docker
RUN yum install -y iptables && \
    wget https://download.docker.com/linux/static/stable/x86_64/docker-19.03.8.tgz && \
    tar -zxvf docker-19.03.8.tgz && mv docker/* /usr/bin && rm -rf docker && rm -f docker-19.03.8.tgz

# configure the rune runtime of docker
RUN mkdir -p /etc/docker && \
    echo -e "{\n\t\"runtimes\": {\n\t\t\"rune\": {\n\t\t\t\"path\": \"/usr/local/bin/rune\",\n\t\t\t\"runtimeArgs\": []\n\t\t}\n\t}\n}" >> /etc/docker/daemon.json

# configure Alibaba Cloud TEE SDK yum repo
RUN yum-config-manager --add-repo \
    https://enclave-cn-beijing.oss-cn-beijing.aliyuncs.com/repo/alinux/enclave-expr.repo

# install Intel SGX SDK and DCAP
RUN yum install --nogpgcheck -y \
    libsgx-uae-service libsgx-dcap-default-qpl \
    libsgx-dcap-quote-verify libsgx-dcap-ql

# install Alibaba Cloud TEE SDK
RUN yum install --nogpgcheck -y teesdk

RUN echo "source /opt/alibaba/teesdk/intel/sgxsdk/environment" >> /root/.bashrc
RUN ln -sf /usr/bin/cmake3 /usr/bin/cmake

# install OPA go dependencies
RUN go get github.com/open-policy-agent/opa@v0.30.2
RUN curl -L -o opa https://openpolicyagent.org/downloads/v0.30.2/opa_linux_amd64_static
RUN chmod 755 ./opa && mv opa /usr/local/bin/
