FROM registry.cn-hangzhou.aliyuncs.com/alinux/aliyunlinux

LABEL maintainer="YiLin Li <YiLin.Li@linux.alibaba.com>"

# Install alinux-release-experimentals prior to others to work around
# the issue "Error: Package: glibc-2.17-323.1.al7.i686 (updates)"
RUN yum clean all && yum install -y alinux-release-experimentals

ENV PROTOBUF_VERSION 2.5.0
ENV PROTOBUF_C_VERSION 1.0.2

RUN yum install -y wget make libseccomp-devel openssl git autoconf libtool \
    openssl-devel binutils-devel rpm-build yum-utils file devtoolset-9-toolchain \
    protobuf-c-devel-$PROTOBUF_C_VERSION protobuf-c-$PROTOBUF_C_VERSION clang which

RUN echo "source /opt/rh/devtoolset-9/enable" > /root/.bashrc

WORKDIR /root

RUN mkdir /root/gopath

# install go
RUN wget https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz && \
    tar -zxvf go1.14.2.linux-amd64.tar.gz -C /usr/lib && \
    rm -rf go1.14.2.linux-amd64.tar.gz

# configure GOPATH and GOROOT
ENV GOROOT       /usr/lib/go
ENV GOPATH       /root/gopath
ENV PATH         $PATH:$GOROOT/bin:$GOPATH/bin
ENV GO111MODULE  on

# install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
ENV PATH         /root/.cargo/bin:$PATH

# install docker
RUN yum install -y iptables && \
    wget https://download.docker.com/linux/static/stable/x86_64/docker-19.03.8.tgz && \
    tar -zxvf docker-19.03.8.tgz && mv docker/* /usr/bin && rm -rf docker && rm docker-19.03.8.tgz

# configure the rune runtime of docker
RUN mkdir -p /etc/docker && \
    echo -e "{\n\t\"runtimes\": {\n\t\t\"rune\": {\n\t\t\t\"path\": \"/usr/local/bin/rune\",\n\t\t\t\"runtimeArgs\": []\n\t\t}\n\t}\n}" >> /etc/docker/daemon.json

# configure Alibaba Cloud TEE SDK yum repo
RUN yum-config-manager --add-repo \
	https://enclave-cn-beijing.oss-cn-beijing.aliyuncs.com/repo/alinux/enclave-expr.repo

# install SGX Runtime
RUN yum install --nogpgcheck -y libsgx-ae-le libsgx-ae-pce libsgx-ae-qe3 libsgx-ae-qve \
    libsgx-aesm-ecdsa-plugin libsgx-aesm-launch-plugin libsgx-aesm-pce-plugin libsgx-aesm-quote-ex-plugin \
    libsgx-dcap-default-qpl libsgx-dcap-ql libsgx-dcap-quote-verify \
    libsgx-enclave-common libsgx-launch libsgx-pce-logic libsgx-qe3-logic libsgx-quote-ex \
    libsgx-ra-network libsgx-ra-uefi libsgx-uae-service libsgx-urts sgx-ra-service \
    sgx-aesm-service

# install Alibaba Cloud TEE SDK
RUN yum install --nogpgcheck -y teesdk

RUN echo "source /opt/alibaba/teesdk/intel/sgxsdk/environment" >> /root/.bashrc
