name: Build runtime testing image

# This is a manual trigger.
on:
  workflow_dispatch:
    inputs:
      inclavare_containers_version:
        description: 'The version of inclavare containers image'
        required: true

jobs:
  build-skeleton-runtime-testing-image:
    # Run all steps in the compilation testing containers
    strategy:
      matrix:
        os: [ubuntu18.04, centos8.2, alinux2]

    # GitHub Actions doesn't have CentOS VM provided
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Because "Build and push" step `context` field can't be subdir,
      # we need to copy files needed by dockerfile to root dir of the project
      - name: Copy context for docker build
        run: |
          cp -r .github/workflows/docker .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.TEST_DOCKER_USERNAME }}
          password: ${{ secrets.TEST_DOCKER_PASSWORD }}

      - name: Build and push the image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile-skeleton-runtime-testing-${{ matrix.os }}
          platforms: linux/amd64
          push: true
          tags: runetest/skeleton-runtime-testing:${{ github.event.inputs.inclavare_containers_version }}-${{ matrix.os }}

  build-enclave-tls-runtime-testing-image:
    # Run all steps in the compilation testing containers
    strategy:
      matrix:
        os: [ubuntu18.04, centos8.2]

    # GitHub Actions doesn't have CentOS VM provided
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Because "Build and push" step `context` field can't be subdir,
      # we need to copy files needed by dockerfile to root dir of the project
      - name: Copy context for docker build
        run: |
          cp -r .github/workflows/docker .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.TEST_DOCKER_USERNAME }}
          password: ${{ secrets.TEST_DOCKER_PASSWORD }}

      - name: Build and push the image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile-enclave-tls-runtime-testing-${{ matrix.os }}
          platforms: linux/amd64
          push: true
          tags: runetest/enclave-tls-runtime-testing:${{ github.event.inputs.inclavare_containers_version }}-${{ matrix.os }}

  build-rats-tls-runtime-testing-image:
    # Run all steps in the compilation testing containers
    strategy:
      matrix:
        os: [ubuntu18.04, centos8.2]

    # GitHub Actions doesn't have CentOS VM provided
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Because "Build and push" step `context` field can't be subdir,
      # we need to copy files needed by dockerfile to root dir of the project
      - name: Copy context for docker build
        run: |
          cp -r .github/workflows/docker .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.TEST_DOCKER_USERNAME }}
          password: ${{ secrets.TEST_DOCKER_PASSWORD }}

      - name: Build and push the image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile-rats-tls-runtime-testing-${{ matrix.os }}
          platforms: linux/amd64
          push: true
          tags: runetest/rats-tls-runtime-testing:${{ github.event.inputs.inclavare_containers_version }}-${{ matrix.os }} 
